export interface Contest {
    id?: number; // Optional, since it might be auto-generated by the backend
    tag: string;
    fromDate: string; // ISO date string (YYYY-MM-DD)
    toDate: string;   // ISO date string (YYYY-MM-DD)
    timestamp: string;
  }
  